revised wait logic
exit with code 1 if any host:port pair times out

diff --git a/wait b/wait
--- a/wait
+++ b/wait
@@ -2,52 +2,48 @@
 
 set -e
 
-DEFAULT_TIMEOUT=30
+timeout=${TIMEOUT:-30}
 
-ports=$PORTS
+# our target format is a newline-delimited list where each item is "host:ip"
+if [ -z "$TARGETS" ]; then
+  # empty TARGETS variable will default to checking all host/ports exposed
+  uris=$(env | grep _TCP= | cut -d= -f2 | cut -c7- )
 
-# set the per host:port connection timeout
-if [ -n "$TIMEOUT" ]; then
-  timeout=$TIMEOUT
-else
-  timeout=$DEFAULT_TIMEOUT
-fi
-
-# empty ports variable will default to checking for exactly one port
-if [ -z "$ports" ]; then
-  ports=$(env | grep _TCP_PORT | cut -d = -f 2)
-
-  if [ $(echo $ports | wc -w) -gt 1 ]; then
-    echo 'The linked container exports more than one port. Exiting'
+  if [ $(echo $ports | wc -w) -lt 1 ]; then
+    echo "The linked container(s) export no ports and you didn't specify any manual targets. Exiting" >&2
     exit 1
   fi
+else
+  uris=$(echo $TARGETS | sed -e 's/,/ /g' -e 's/\s+/\n/g' | uniq)
 fi
 
-# find the host(s) associated with each of the ports
-# and wait until that port responds
-if [ -n "$ports" ]; then
-  echo "waiting for TCP connections"
+# wait for each target
+if [ -z "$uris" ]; then
+  echo "No wait targets found. Exiting" >&2
+  exit 1
+fi
 
-  for port in $(echo $ports | sed -e 's/,/ /g' -e 's/\s+/\n/g' | uniq)
+for uri in $uris
+do
+  host=$(echo $uri | cut -d: -f1)
+  port=$(echo $uri | cut -d: -f2)
+  [ -n "${host}" ]
+  [ -n "${port}" ]
+  echo -n "Waiting for ${uri}  ."
+  seconds=0
+  while [ "$seconds" -lt "$timeout" ] && ! nc -z -w1 $host $port
   do
-    for host in $(env | grep PORT_${port}_TCP_ADDR | cut -d = -f 2 | uniq)
-    do
-      seconds=0
-      while [ "$seconds" -lt "$timeout" ] && ! nc -z -w1 $host $port
-      do
-        echo -n .
-        seconds=$((seconds+1))
-        sleep 1
-      done
-
-      if [ "$seconds" -lt "$timeout" ]; then
-        echo -n "$host:$port up!"
-      else
-        echo -n "$host:$port WARN: unable to connect"
-      fi
-      echo -n '\n'
-    done
+    echo -n .
+    seconds=$((seconds+1))
+    sleep 1
   done
-fi
 
-exit
+  if [ "$seconds" -lt "$timeout" ]; then
+    echo "  $host:$port up!"
+  else
+    echo "  $host:$port ERROR: unable to connect" >&2
+    exit 1
+  fi
+done
+echo "Everything is up"
+exit 0
